### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by iammohitsakhuja** [mohitsakhuja/weather-app#4]
The main layout page of the app needs to have two sections. The one on the left will display individual cards for each city, and the right section will display the detailed info of the selected card.

**Comment by ghost** [comment]
I would like to work on this issue.

**Comment by iammohitsakhuja** [comment]
Go ahead 👍

**Comment by iammohitsakhuja** [comment]
Taking into account some recent developments, I'm reassigning this issue to myself. You can still contribute to other future issues 🙂

**Comment by iammohitsakhuja** [comment]
Waiting for updates on #6. Rest is complete. Closing it now.
